/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: process.env.DARK_MODE ? process.env.DARK_MODE : 'class',
  content: ['./app/**/*.{html,js,jsx,ts,tsx,mdx}', './src/**/*.{html,js,jsx,ts,tsx,mdx}'],
  presets: [require('nativewind/preset')],
  important: 'html',
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--color-background)/<alpha-value>)',
        foreground: 'rgb(var(--color-foreground)/<alpha-value>)',
        card: 'rgb(var(--color-card)/<alpha-value>)',
        'card-foreground': 'rgb(var(--color-card-foreground)/<alpha-value>)',
        popover: 'rgb(var(--color-popover)/<alpha-value>)',
        'popover-foreground': 'rgb(var(--color-popover-foreground)/<alpha-value>)',
        primary: 'rgb(var(--color-primary)/<alpha-value>)',
        'primary-foreground': 'rgb(var(--color-primary-foreground)/<alpha-value>)',
        secondary: 'rgb(var(--color-secondary)/<alpha-value>)',
        'secondary-foreground': 'rgb(var(--color-secondary-foreground)/<alpha-value>)',
        muted: 'rgb(var(--color-muted)/<alpha-value>)',
        'muted-foreground': 'rgb(var(--color-muted-foreground)/<alpha-value>)',
        accent: 'rgb(var(--color-accent)/<alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground)/<alpha-value>)',
        destructive: 'rgb(var(--color-destructive)/<alpha-value>)',
        'destructive-foreground': 'rgb(var(--color-destructive-foreground)/<alpha-value>)',
        border: 'rgb(var(--color-border)/<alpha-value>)',
        input: 'rgb(var(--color-input)/<alpha-value>)',
        ring: 'rgb(var(--color-ring)/<alpha-value>)',
        tertiary: 'rgb(var(--color-tertiary)/<alpha-value>)',
        success: 'rgb(var(--color-success)/<alpha-value>)',
        warning: 'rgb(var(--color-warning)/<alpha-value>)',
        info: 'rgb(var(--color-info)/<alpha-value>)',
      },
      fontFamily: {
        heading: 'undefined',
        body: 'undefined',
        mono: 'undefined',
        jakarta: ['var(--font-plus-jakarta-sans)'],
        roboto: ['var(--font-roboto)'],
        code: ['var(--font-source-code-pro)'],
        inter: ['var(--font-inter)'],
        'space-mono': ['var(--font-space-mono)'],
      },
      fontWeight: {
        extrablack: '950',
      },
      fontSize: {
        '2xs': '10px',
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 8px)',
        '2xl': 'calc(var(--radius) + 16px)',
        '3xl': 'calc(var(--radius) + 24px)',
        full: '9999px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
